### Login
POST http://localhost:3000/coreusuario/login
Content-Type: application/json

{
  "nickname": "admin",
  "clave": "G4system2023"
}
# "clave": "G4system2023"

### Opciones por usuario id
GET http://localhost:3000/coreusuario/opcionesmenubyidusuario/1

curl --location 'http://localhost:3000/coreusuario/login' \
--header 'Content-Type: application/json' \
--data '{"nickname": "admin", "clave": "1234"}'

curl --location 'http://localhost:3000/coreusuario/opcionesmenubyidusuario/1'